### ISSUE TITLE
Wrong initialization of DOFs in "Default"

### ISSUE THREAD

**Issue by v-morlock** [petrikosk/rsruckig#6]
Hey Petri!

Thanks for getting back and for adding the DOFs as const-generics! I just started to play with rsruckig again and found that the "Default" implementation seems to not always respect the DOFs (e.g. `InputParameter.enabled` does initialize an empty vector when using `..Default::default()`)

I'd be happy to provide a PR to fix that but i wanted to let you know first, in case you've got any thoughts on it and to quickly check whether you'd accept such a fix.

Thanks and best,
Valentin

**Comment by petrikosk** [comment]
Please see this commit: /commit/c719101d084d84a1b303c9eef8e66520a2a2f748
